### ISSUE TITLE
Stacking UX

### ISSUE THREAD

**Issue by skull-squadron** [quemb/QMBTabs#3]
Current, stacked tabs completely obscure each other.

```
/ tab n-3 \
/ tab n-2 \
/ tab n-1 \
```

It seems desirable to offer an affordance like so the user can see there are others:

```
/ tab n-3 \
  / tab n-2 \
    / tab n-1 \
```

**Comment by skull-squadron** [comment]
I've implemented it https://github.com/steakknife/QMBTabs in case anyone wants it along with badges.

**Comment by tonimoeckel** [comment]
Thanks steakknife!!! 
Do you want to send me a pull request? I'm happy to merge it.

**Comment by skull-squadron** [comment]
Boom.
